// chrome-extension/src/background/agent/platforms/naukri/selectors.ts

export const NAUKRI_SELECTORS = {
  // Session & Login indicators
  LOGIN_CONTAINER: [
    'form[name="login-form"]',
    '#usernameField',
    'input[placeholder*="Username" i]',
    '.login-layer',
    '.nI-gNb-header__login-btn',
  ],
  LOGGED_IN_INDICATORS: [
    '.nI-gNb-drawer',
    '.nI-gNb-user-img',
    'a[title="View Profile"]',
    '.user-name',
    '.nI-gNb-header__user-menu',
  ],

  // Job Search Results
  JOB_TUPLES: ['div.srp-jobtuple-wrapper', 'article.jobTuple', 'div.cust-job-tuple', 'div[data-job-id]', 'div.tuple'],
  JOB_TITLE: ['a.title', '.title', 'h2 a', 'a[data-job-id]'],
  COMPANY_NAME: ['a.comp-name', '.comp-name', 'a.subTitle', '.subTitle', '.org'],
  LOCATION: ['span.loc-wrap', 'span.locWdn', '.loc', '.location'],
  EXPERIENCE: ['span.exp-wrap', 'span.expwdth', '.exp', '.experience'],
  SALARY: ['span.sal-wrap', 'span.sal', '.sal', '.salary'],
  TAGS: ['ul.tags-gt li', '.tag-li', '.tags li', '.badge'],

  // Job Details Page & Apply Buttons
  PRIMARY_APPLY_BUTTON: [
    'button#apply-button',
    'button.apply-button',
    'button[id*="apply" i]',
    '.apply-button-container button',
    '.apply-pwa-btn',
    'button.waves-effect',
  ],
  EXTERNAL_APPLY_INDICATORS: [
    'apply on company site',
    'apply on employer website',
    'company website',
    'redirecting to employer',
  ],
  ALREADY_APPLIED_INDICATORS: ['already applied', 'you applied', 'applied on', '.applied-badge', '.already-applied'],
  SUCCESS_INDICATORS: [
    'successfully applied',
    'application sent',
    'applied successfully',
    'your application has been sent',
    'you have applied',
    '.apply-message',
  ],

  // Questionnaire / Popups / Chatbot / Drawer
  MODAL_CONTAINER: [
    'div.drawer-wrapper',
    'div[class*="drawer-wrapper" i]',
    'div[class*="apply-drawer" i]',
    'div[class*="applyDrawer" i]',
    'div[class*="applyContainer" i]',
    'div[class*="apply-container" i]',
    'div[class*="custom-question" i]',
    'div.apply-message-container',
    'div.chatbot-container',
    'div.chatbot_container',
    'div[class*="chatbot" i]',
    'div[class*="chat-bot" i]',
    'div[class*="bot-container" i]',
    'div[class*="bot_container" i]',
    'div[class*="bot-wrapper" i]',
    'div.apply-modal',
    'div.layer-wrap',
    'div[role="dialog"]',
    'div[class*="modal" i][class*="apply" i]',
    'div[class*="chat" i][class*="wrap" i]',
  ],
  SUBMIT_BUTTON: [
    'button.apply-message-btn',
    'button.chatbot-submit',
    'button[type="submit"]',
    'button.save-apply',
    'button.save-btn',
    '.submit-btn',
    'button[class*="save" i]',
    'button[class*="submit" i]',
    'button[class*="apply" i]',
    'button[class*="chat" i][class*="btn" i]',
  ],
  SKIP_QUESTION_BUTTON: [
    'button[class*="skip" i]',
    'a[class*="skip" i]',
    'span[class*="skip" i]',
    'div[class*="skip" i]',
    '[data-qa*="skip" i]',
  ],
  CHATBOT_QUESTION_BUBBLE: [
    'div[class*="msg-text" i]',
    'div[class*="chat-bubble" i]',
    'div[class*="bot-msg" i]',
    'div[class*="msgItem" i]',
    'div[class*="message" i]',
    'div[class*="msg" i]',
    'p[class*="msg" i]',
    'span[class*="msg" i]',
  ],
  CHATBOT_OPTIONS: [
    'div[class*="option" i]',
    'div[class*="chip" i]',
    'div[class*="pill" i]',
    'li[class*="option" i]',
    'div[class*="choice" i]',
    'label[class*="option" i]',
    'button[class*="option" i]',
    'div[class*="bot-options" i] > *',
    'ul[class*="bot-options" i] > li',
  ],
};
