/**
 * Comprehensive predefined tech skills list for Career Brain autocomplete.
 * Covers programming languages, frontend/backend frameworks, databases, cloud platforms, DevOps, AI/ML, and tools.
 */
export const PREDEFINED_TECH_SKILLS: string[] = [
  // Programming Languages
  'C',
  'C++',
  'C#',
  'Clojure',
  'Dart',
  'Elixir',
  'Erlang',
  'Go (Golang)',
  'GraphQL',
  'Groovy',
  'Haskell',
  'HTML5 / CSS3',
  'Java',
  'JavaScript',
  'Kotlin',
  'Lua',
  'Objective-C',
  'Perl',
  'PHP',
  'Python',
  'R',
  'Ruby',
  'Rust',
  'Scala',
  'Shell / Bash',
  'Solidity',
  'SQL',
  'Swift',
  'TypeScript',

  // Frontend Libraries & Frameworks
  'Angular',
  'Ant Design',
  'Astro',
  'Bootstrap',
  'Chakra UI',
  'D3.js',
  'Ember.js',
  'Emotion',
  'Gatsby',
  'HTML5',
  'Ionic',
  'jQuery',
  'Material-UI (MUI)',
  'MobX',
  'Next.js',
  'Nuxt.js',
  'Preact',
  'Radix UI',
  'React',
  'React Native',
  'React Query / TanStack Query',
  'Redux / Redux Toolkit',
  'Relay',
  'Remix',
  'RxJS',
  'Sass / SCSS',
  'Shadcn UI',
  'SolidJS',
  'Storybook',
  'Styled Components',
  'Svelte',
  'SvelteKit',
  'Tailwind CSS',
  'Three.js',
  'Vite',
  'Vue.js',
  'Webpack',
  'Zustand',

  // Backend Frameworks & Runtimes
  '.NET Core / ASP.NET',
  'Actix-web',
  'Apollo GraphQL',
  'Bun',
  'Celery',
  'Deno',
  'Django',
  'Django REST Framework',
  'Elixir Phoenix',
  'Express.js',
  'FastAPI',
  'Fastify',
  'Fiber (Go)',
  'Flask',
  'Gin (Go)',
  'Go Fiber',
  'gRPC',
  'Hapi.js',
  'Koa.js',
  'Laravel',
  'NestJS',
  'Node.js',
  'Prisma ORM',
  'RESTful APIs',
  'Ruby on Rails',
  'Spring Boot',
  'Struts',
  'Swoole',
  'Symfony',
  'tRPC',
  'TypeORM',
  'WebSockets',

  // Databases, Data Stores & Caching
  'Apache Cassandra',
  'Apache CouchDB',
  'ClickHouse',
  'CockroachDB',
  'Couchbase',
  'DynamoDB',
  'Elasticsearch',
  'Firebase Realtime Database',
  'Firestore',
  'InfluxDB',
  'MariaDB',
  'Memcached',
  'MongoDB',
  'Mongoose',
  'MySQL',
  'Neo4j',
  'OpenSearch',
  'Oracle Database',
  'PostgreSQL',
  'Redis',
  'SQLite',
  'Supabase',
  'TimescaleDB',

  // Cloud, Infrastructure & DevOps
  'Amazon Web Services (AWS)',
  'Ansible',
  'Apache Kafka',
  'Apache Spark',
  'ArgoCD',
  'AWS Lambda / Serverless',
  'CircleCI',
  'Cloudflare / Cloudflare Workers',
  'Datadog',
  'DigitalOcean',
  'Docker',
  'Elastic Beanstalk',
  'GCP (Google Cloud Platform)',
  'Git',
  'GitHub Actions',
  'GitLab CI/CD',
  'Grafana',
  'Helm',
  'Heroku',
  'Jenkins',
  'Kubernetes (K8s)',
  'Linux / Unix Administration',
  'Microsoft Azure',
  'Nginx',
  'OpenShift',
  'Prometheus',
  'Puppet',
  'RabbitMQ',
  'Sentry',
  'Terraform',
  'Travis CI',
  'Vagrant',
  'Vercel',

  // AI, Machine Learning & Data Science
  'Apache Airflow',
  'Anthropic Claude API',
  'Computer Vision',
  'Deep Learning',
  'Generative AI',
  'Hugging Face Transformers',
  'LangChain',
  'Large Language Models (LLMs)',
  'LlamaIndex',
  'Machine Learning',
  'Matplotlib',
  'MLflow',
  'Natural Language Processing (NLP)',
  'NumPy',
  'Ollama',
  'OpenAI API',
  'OpenCV',
  'Pandas',
  'PyTorch',
  'RAG (Retrieval-Augmented Generation)',
  'Scikit-Learn',
  'Seaborn',
  'TensorFlow',
  'Vector Databases (Chroma / Pinecone / Qdrant / Weaviate)',
  'Weights & Biases',

  // Testing & Quality Assurance
  'Chai',
  'Cypress',
  'Jest',
  'Jasmine',
  'JUnit',
  'k6',
  'Mocha',
  'Playwright',
  'Postman',
  'Puppeteer',
  'Pytest',
  'Selenium WebDriver',
  'Supertest',
  'TestNG',
  'Vitest',

  // Mobile & Desktop App Development
  'Android SDK',
  'Capacitor',
  'Cordova',
  'Electron.js',
  'Expo',
  'Flutter',
  'iOS SDK',
  'Kotlin Multiplatform',
  'SwiftUI',
  'Tauri',

  // Architecture, Security & Methodologies
  'Agile / Scrum',
  'Clean Architecture',
  'Domain-Driven Design (DDD)',
  'Event-Driven Architecture',
  'JSON Web Tokens (JWT)',
  'Microservices Architecture',
  'OAuth 2.0 / OpenID Connect',
  'OWASP Security Practices',
  'Role-Based Access Control (RBAC)',
  'System Design',
  'Test-Driven Development (TDD)',
  'Web Security & Pen Testing',
];
