// chrome-extension/src/background/agent/platforms/indeed/selectors.ts

export const INDEED_SELECTORS = {
  // Session & Auth
  LOGGED_IN_INDICATORS: [
    'a[data-gnav-element-name="Profile"]',
    'button[data-gnav-element-name="Profile"]',
    'button[id*="user-menu" i]',
    'a[href*="/account" i]',
    '.gnav-AccountMenu',
  ],
  LOGIN_CONTAINER: ['form[action*="/auth" i]', 'input[name="__email"]', '#login-email-input', 'div.signin-container'],

  // Captcha & Cloudflare bot challenges
  CAPTCHA_CONTAINERS: [
    'iframe[src*="cloudflare" i]',
    'iframe[src*="hcaptcha" i]',
    'iframe[src*="recaptcha" i]',
    'iframe[src*="turnstile" i]',
    'div#challenge-running',
    'div.cf-turnstile',
    '#challenge-form',
    '#challenge-stage',
    'div[id*="turnstile" i]',
    '.cf-turnstile-wrapper',
  ],

  // Job Search Results
  JOB_CARDS: ['div.job_seen_beacon', 'div.cardOutline', 'div.jobsearch-SerpJobCard', 'div[data-jk]'],
  JOB_TITLE: ['h2.jobTitle a', 'a.jcs-JobTitle', 'a[data-jk]', 'span[id^="jobTitle"]'],
  COMPANY_NAME: ['span[data-testid="company-name"]', 'span.companyName', '.company_location .companyName'],
  LOCATION: ['div[data-testid="text-location"]', 'div.companyLocation', '.company_location .companyLocation'],
  SALARY: ['div.metadata.salary-snippet-container', 'div[data-testid="attribute_snippet_testid"]', '.salary-snippet'],
  EASILY_APPLY_BADGE: [
    'span.iaIcon',
    'div.iaIcon',
    '.ia-badge',
    'span.ia-tag',
    '[data-testid="indeedApply"]',
    '.indeedApply',
    'svg[aria-label*="Easily apply" i]',
    'svg[aria-label*="Apply with your Indeed Resume" i]',
    'span[class*="indeedApply" i]',
    'span[data-testid="myJobsStatePill"]',
  ],

  // Job Detail & Apply Buttons (Specifically Indeed Apply)
  PRIMARY_APPLY_BUTTON: [
    '#indeedApplyButton',
    'button[data-testid="indeedApplyButton"]',
    'button.indeed-apply-button',
    'button.ia-IndeedApplyButton',
    'button[id*="indeedApply" i]',
    'div.jobsearch-IndeedApplyButton button',
    'div[data-testid="indeedApplyButton"] button',
    '[data-testid="jobsearch-IndeedApplyButton"] button',
    'a[data-testid="indeedApplyButton"]',
    'a.indeed-apply-button',
  ],
  EXTERNAL_APPLY_SELECTORS: [
    '#jobsearch-ViewJobButtons-container a[href*="/rc/clk"]',
    '#jobsearch-ViewJobButtons-container a',
    '#jobsearch-ViewJobButtons-container button',
    '#viewJobButtonContainer button',
    '[data-testid="viewJob-applyButton"]',
    'div.jobsearch-JobInfoHeader-actions a[href*="/rc/clk"]',
  ],
  EXTERNAL_APPLY_INDICATORS: [
    'apply on company site',
    'apply on employer website',
    'apply on employer site',
    "apply on employer's website",
    'apply directly on company',
    'continue to apply',
    'apply externally',
  ],
  CARD_EXTERNAL_INDICATORS: [
    'apply on company site',
    'apply on employer website',
    'apply on employer site',
    "apply on employer's website",
  ],
  ALREADY_APPLIED_INDICATORS: [
    'you applied to this job',
    'applied on indeed',
    'you have applied to this job',
    "you've applied to this job",
  ],
  ALREADY_APPLIED_SELECTORS: [
    'div.ia-AppliedBadge',
    'div[class*="AppliedBadge" i]',
    '[data-testid="myJobsStatePill"]',
    'button[disabled*="applied" i]',
    'span[data-testid="myJobsStatePill"]',
    '.jobsearch-JobInfoHeader-actions [class*="applied" i]',
  ],
  SUCCESS_INDICATORS: [
    'your application has been submitted',
    'application submitted',
    'your application was submitted',
    'successfully applied',
    'application was sent',
    'your application has been sent',
    'your application was sent',
    'application sent',
    'you applied to this job',
    'applied on indeed',
    'you have applied',
    "you've applied",
    'application complete',
    'thank you for applying',
    'return to job search',
    'track your application',
    'track this application',
    'track your applications',
    'jobs you might like',
    "we've sent your application",
    'we sent your application',
    'your resume has been submitted',
  ],
  SUCCESS_SELECTORS: [
    'div.ia-AppliedBadge',
    'div[data-testid="post-apply"]',
    'div.ia-PostApply',
    '#post-apply-container',
    'button[disabled*="applied" i]',
    'svg[aria-label*="success" i]',
    'svg[aria-label*="applied" i]',
  ],

  // Multi-Step Apply Modal / Iframe Elements
  MODAL_CONTAINER: ['div#indeedapply-modal', 'div.ia-BasePage', 'div[role="dialog"]', 'iframe[name*="indeedapply"]'],
  FORWARD_BUTTON_SELECTORS: [
    'button[data-testid="continue-button"]',
    'button[data-testid="save-button"]',
    'button[data-testid="save-continue-button"]',
    'button[data-testid="review-button"]',
    'button.ia-continueButton',
    'button.ia-SmartApplyCard-primaryButton',
    'button.ia-SmartApplyCard-saveButton',
    'button[aria-label*="continue" i]',
    'button[aria-label*="next" i]',
    'button[aria-label*="save" i]',
    'button[aria-label*="review" i]',
  ],
  FORWARD_BUTTON_TEXTS: [
    'continue',
    'next',
    'review your application',
    'review application',
    'review',
    'save and continue',
    'save & continue',
    'save',
    'proceed',
    'skip',
  ],
  SUBMIT_BUTTON_SELECTORS: [
    'button[data-testid="submit-button"]',
    'button[data-testid*="submit" i]',
    'button.ia-submitButton',
    'button.ia-SubmitButton',
    'button[class*="submitButton" i]',
    'button[class*="submit-button" i]',
    'button[aria-label*="submit" i]',
  ],
  SUBMIT_BUTTON_TEXTS: [
    'submit your application',
    'submit application',
    'submit my application',
    'submit to employer',
    'submit',
  ],
};
